[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tyru/vim-altercmd'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'bkad/CamelCaseMotion'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-rbenv'

[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'danchoi/ri.vim'

[[plugins]]
repo = 'kana/vim-altr'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
let g:LanguageClient_serverCommands = {
    \ 'vue': ['vls'],
    \ 'html': [],
    \ 'javascript': [],
    \ 'css': [],
    \ }
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
  set hidden
  let g:LanguageClient_serverCommands = {
      \ 'vue': ['vls'],
      \ }
  autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
